<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Calendar;
use Illuminate\Support\Facades\DB;

class CalendarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Langkah 1: Bersihkan tabel terlebih dahulu untuk menghindari duplikasi
        DB::table('calendar')->truncate();

        // Langkah 2: Siapkan daftar unik Nama Diklat dari data pembimbing
        $uniqueTitles = [
            'BIMTEK Tenaga Fungsional Persiapan Ujian Dinas dan Ujian Peningkatan Pendidikan bagi Tenaga Kependidikan Tetap Non ASN UNNES',
            'BIMTEK PEMBUATAN POLICY BRIEF BAGI ANALIS KEBIJAKAN PEMERINTAH KABUPATEN GROBOGAN',
            'Ceramah Isu Strategis dan Kepemimpinan Kinerja Oganisasi',
            'Ceramah Isu Strategis dan Kepemimpinan Pelayanan Publik',
            'Ceramah Wawasan Kebangsaan Kepemimpinan Pancasila dan Integritas',
            'DF Analis Kepegawaian Keahlian',
            'DF Dasar Alih Penyuluh Pertanian',
            'DF Distric Food Inspector (Pengawasan Pangan Daerah)',
            'DF Higiene Sanitasi Makanan dan Minuman',
            'DF Peningkatan Kinerja Penyuluh Sosial Dalam Penanggulangan Kemiskinan',
            'DF Penyuluh Keamanan Pangan',
            'DF Surveilans Kesehatan',
            'DF TOT Monitoring dan Evaluasi Pelayanan Administrasi Terpadu Kecamatan',
            'DF TOT Penyusunan Dokumen Akreditasi Puskesmas',
            'DF TOT Revolusi Mental',
            'Diagnosa Organisasi',
            'Diklat Calon Widyaswara',
            'Diklat Dasar Ahli Penyuluh Pertanian Angkt.1',
            'Diklat Dasar Fungs,Penyuluh pertanian terampil Angkt.1',
            'Diklat Dasar Fungsional Penyuluh Pertanian Ahli',
            'Diklat Dasar Fungsional Penyuluh Pertanian Ahli ANGK. 1',
            'Diklat Dasar Fungsional Penyuluh Pertanian Ahli ANGK. 2',
            'Diklat Dasar Fungsional Penyuluh Pertanian Terampil',
            'Diklat Dasar Satpol PP Pola 150 jam Angk.1',
            'Diklat Distric Food Inspector (Pengawasan Pangan Daerah) Angkt.1',
            'Diklat Jab.Fungs.Perawat jenjang Ahli Angkt.1',
            'Diklat Jabatan Fungs.Bidan Angk.1',
            'Diklat Jabatan Fungsional Bidan Jenjang Ahli',
            'Diklat Jabatan Fungsional Nutrisionis Jenjang Ahli',
            'Diklat Jabatan Fungsional Pengawas Penyelenggaraan Urusan Pemerintahan di Daerah (P2UPD)',
            'Diklat Jabatan Fungsional Perawat Jenjang Ahli',
            'Diklat Jabatan Fungsional Sanitarian Jenjang Ahli ANGK. 1',
            'Diklat Jabatan Fungsional Sanitarian Jenjang Ahli ANGK. 2',
            'Diklat Jabatan Fungsional Sanitarian Jenjang Terampil ANGK. 1',
            'Diklat Jabatan Fungsional Sanitarian Jenjang Terampil ANGK. 2',
            'Diklat JabFungs.Nutrisionis Jenjang Ahli Angkt.1',
            'Diklat Kades Angk.7',
            'Diklat Pengangkatan Jabatan Fungsional Administrator Kesehatan',
            'Diklat Penyuluh Keamanan Pangan Angkt.1',
            'Diklat Pim II Angk.5',
            'Diklat Pim II Angk.6',
            'Diklat Pim III Angk.20',
            'Diklat Pim III Angk.21',
            'Diklat Pim III Angk.22',
            'Diklat Pim III Angk.24',
            'Diklat Pim III Angk.26',
            'Diklat Pim III Angk.27',
            'Diklat Pim IV Angk.55',
            'Diklat Pim IV Angk.57',
            'Diklat Pim IV Angk.58',
            'Diklat Pim IV Angk.59',
            'Diklat Pim IV Angk.74',
            'Diklat Pim IV Angk.76',
            'Diklat Pim IV Angk.78',
            'Diklat Pim IV Angk.79',
            'Diklat Pim IV Angk.82',
            'Diklat Pim IV Angk.83',
            'Diklat Pim IV Angk 90',
            'Diklat Pim IV Angk XC',
            'Diklat Pim IV Angk XCII',
            'Diklat Prajabat Gol.I,II,III Formasi K1/K2 Angk.10',
            'Diklat Prajabat Gol.I,II,III Formasi K1/K2 Angk.11',
            'Diklat Prajabat Gol.I,II,III Formasi K1/K2 Angk.5',
            'Diklat Prajabat Gol.I,II,III Formasi K1/K2 Angk.6',
            'Diklat Prajabat Gol.I,II,III Formasi K1/K2 Angk.7',
            'Diklat Prajabat Gol.I,II,III Formasi K1/K2 Angk.8',
            'Diklat Prajabat Golongan II Formasi Umum Angk.10',
            'Diklat Prajabat Golongan II Formasi Umum Angk.6',
            'Diklat Prajabat Golongan II Formasi Umum Angk.7',
            'Diklat Prajabat Golongan II Formasi Umum Angk.8',
            'Diklat Prajabat Golongan II Formasi Umum Angk.9',
            'Diklat Prajabat Golongan III Formasi Umum Angk.21',
            'Diklat Prajabat Golongan III Formasi Umum Angk.22',
            'Diklat Prajabat Golongan III Formasi Umum Angk.23',
            'Diklat Prajabatan CPNS Gol II Angkatan I',
            'Diklat Prajabatan CPNS Gol II Angkatan II',
            'Diklat Prajabatan CPNS Gol II Angkatan III',
            'Diklat Prajabatan CPNS Gol II Angkatan IV',
            'Diklat Prajabatan CPNS Gol II Angkatan IX',
            'Diklat Prajabatan CPNS Gol II Angkatan V',
            'Diklat Prajabatan CPNS Gol II Angkatan VI',
            'Diklat Prajabatan CPNS Gol II Angkatan VII',
            'Diklat Prajabatan CPNS Gol II Angkatan VIII',
            'Diklat Prajabatan CPNS Gol II Angkatan X',
            'Diklat Prajabatan CPNS Gol II Angkatan XI',
            'Diklat Prajabatan CPNS Gol II Angkatan XII',
            'Diklat Prajabatan CPNS Gol II Angkatan XIII',
            'Diklat Prajabatan CPNS Gol II Angkatan XIV',
            'Diklat Prajabatan CPNS Gol II Angkatan XIX',
            'Diklat Prajabatan CPNS Gol II Angkatan XL',
            'Diklat Prajabatan CPNS Gol II Angkatan XLI',
            'Diklat Prajabatan CPNS Gol II Angkatan XLVII',
            'Diklat Prajabatan CPNS Gol II Angkatan XLVIII',
            'Diklat Prajabatan CPNS Gol II Angkatan XV',
            'Diklat Prajabatan CPNS Gol II Angkatan XVI',
            'Diklat Prajabatan CPNS Gol II Angkatan XVII',
            'Diklat Prajabatan CPNS Gol II Angkatan XVIII',
            'Diklat Prajabatan CPNS Gol II Angkatan XXI',
            'Diklat Prajabatan CPNS Gol II Angkatan XXII',
            'Diklat Prajabatan CPNS Gol II Angkatan XXIII',
            'Diklat Prajabatan CPNS Gol II Angkatan XXVI',
            'Diklat Prajabatan CPNS Gol II Angkatan XXVII',
            'Diklat Prajabatan CPNS Gol II Angkatan XXXV',
            'Diklat Prajabatan CPNS Gol II Angkatan XXXVI',
            'Diklat Prajabatan CPNS Gol II dan III Angkatan XC',
            'Diklat Prajabatan CPNS Gol II dan III Angkatan XCI',
            'Diklat Prajabatan CPNS Gol II dan III Angkatan XCII',
            'Diklat Prajabatan CPNS Gol II dan III Angkatan XCIII',
            'Diklat Prajabatan CPNS Gol II dan III Angkatan XCIV',
            'Diklat Prajabatan CPNS Gol II dan III Angkatan XCV',
            'Diklat Prajabatan CPNS Gol. II Angkatan IX',
            'Diklat Prajabatan CPNS Gol. II Angkatan X',
            'Diklat Prajabatan CPNS Gol. II Angkatan XVI',
            'Diklat Prajabatan CPNS Gol. II Angkatan XVII',
            'Diklat Prajabatan CPNS Gol. II Angkatan XVIII',
            'Diklat Prajabatan CPNS Gol. II Angkatan XV',
            'Diklat Prajabatan CPNS Gol. III Angk. 1',
            'Diklat Prajabatan CPNS Gol. III Angk. 10',
            'Diklat Prajabatan CPNS Gol. III Angk. 11',
            'Diklat Prajabatan CPNS Gol. III Angk. 13',
            'Diklat Prajabatan CPNS Gol. III Angk. 14',
            'Diklat Prajabatan CPNS Gol. III Angk. 2',
            'Diklat Prajabatan CPNS Gol. III Angk. 3',
            'Diklat Prajabatan CPNS Gol. III Angk. 4',
            'Diklat Prajabatan CPNS Gol. III Angk. 7',
            'Diklat Prajabatan CPNS Gol. III Angk. 8',
            'Diklat Prajabatan CPNS Gol. III Angk. 9',
            'Diklat Prajabatan CPNS Gol.III Angk. 5',
            'Diklat Prajabatan CPNS Gol.III Angk. 6',
            'Diklat Prajabatan CPNS Gol.III Angk.12',
            'Diklat Prajabatan Gol II Angk.1',
            'Diklat Prajabatan Gol III Angk.1',
            'Diklat Prajabatan Gol III Angk.2',
            'Diklat Prajabatan Gol III Angk.3',
            'Diklat Prajabatan Gol III Angk.5',
            'Diklat Prajabatan Gol III Angk.6',
            'Diklat Prajabatan Gol III Angk.8',
            'Diklat Prajabatan Gol III Angk.I',
            'Diklat Prajabatan Gol III Angkt.7',
            'Diklat Prajabatan Gol III angk.4',
            'Diklat Prajab K1/K2 Angkatan 20',
            'Diklat Prajab K1/K2 Angkatan 21',
            'Diklat Prajab K1/K2 Angkatan 22',
            'Diklat Prajab K1/K2 Angkatan 24',
            'Diklat Prajab K1/K2 Angkatan 25',
            'Diklat Prajab K1/K2 Angkatan 26',
            'Diklat Prajab K1/K2 Angkatan 28',
            'Diklat Prajab K1/K2 Angkatan 29',
            'Diklat Prajab K1/K2 Angkatan 30',
            'Diklat Prajab K1/K2 Angkatan 32',
            'Diklat Prajab K1/K2 Angkatan 33',
            'Diklat Prajab K1/K2 Angkatan 34',
            'Diklat Prajab K1/K2 Angkatan 35',
            'Diklat Prajab K1/K2 Angkatan 36',
            'Diklat Tim Penilai Jabatan Fungsional Pustakawan',
            'Diklatpim Tingkat III Angkatan XXIX',
            'Diklatpim Tingkat III Angkatan XXX',
            'Diklatpim Tingkat III Angkatan XXXI',
            'Diklatpim Tingkat III Angkatan XXXII',
            'Diklatpim Tingkat III Angkatan XXXIII',
            'Diklatpim Tingkat III Angkatan XXXIV',
            'Diklatpim Tingkat IV Angkatan C',
            'Diklatpim Tingkat IV Angkatan CI',
            'Diklatpim Tingkat IV Angkatan CIV',
            'Diklatpim Tingkat IV Angkatan CV',
            'Diklatpim Tingkat IV Angkatan CVI',
            'Diklatpim Tingkat IV Angkatan CVII',
            'Diklatpim Tingkat IV Angkatan LXXXVI',
            'Diklatpim Tingkat IV Angkatan XCVI',
            'Diklatpim Tingkat IV Angkatan XCI',
            'Diklatpim Tk. III Angk. III Pemkab Kudus',
            'Diklatpim Tk. III Angk. IV Pemkot Semarang',
            'Diklatpim Tk. IV Angk. I Pemkot Surakarta',
            'Diklatpim Tk. IV Angk. II Pemkab Banjarnegara',
            'Diklatpim Tk. IV Angk. III Pemkab Jepara',
            'Diklatpim Tk. IV Angk. IV Pemkot Pekalongan',
            'Diklatpim Tk. IV Angk. IX Pemkab Cilacap',
            'Diklatpim Tk. IV Angk. VI Pemkab Boyolali',
            'Diklatpim Tk. IV Angk. X Pemkab Grobogan',
            'Diklatpim Tk. IV Angk. XI Pemkab Sukoharjo',
            'Diklatpim Tk. IV Angk. XIII Pemkot Semarang',
            'Diklatpim Tk. IV Angk. XIV Pemkab Banyumas',
            'Diklatpim Tk. IV Angk. XX Pemkab Kudus',
            'Diklatpim Tk. IV Angk. XXI Pemkab Demak',
            'Diklatpim Tk. IV Angk. XXII Pemkot Semarang',
            'Diklatpim Tk. IV Angk. XXIII Pemkot Semarang',
            'Diknis Admins. Dasar bg PNS dlingk.prov.jtg - ANGK.1',
            'Diknis Admins. Dasar bg PNS dlingk.prov.jtg - ANGK.2',
            'Diknis Admins. Dasar bg PNS dlingk.prov.jtg - ANGK.3',
            'Diknis Admins. Dasar bg PNS dlingk.prov.jtg - ANGK.4',
            'Diknis Akuntansi berbasis Akrual Angkt.1',
            'Diknis Akuntansi berbasis Akrual Angkt.2',
            'Diknis Akuntansi berbasis Akural l - ANGK.1',
            'Diknis Akuntansi berbasis Akural l - ANGK.2',
            'Diknis Anjab 1 - ANGK.1',
            'Diknis Anjab ll - ANGK.2',
            'Diknis Anjab Penyusunan Stand.Penggajian.Angkt.1',
            'Diknis Audit Investigasi l - ANGK.1',
            'Diknis Audit Investigasi Il - ANGK.2',
            'Diknis Bahasa Inggris tk. Dasar',
            'Diknis Bend. Keuangan Daerah ll - ANGK.2',
            'Diknis Bendahara Keuangan Daerah I - ANGK.1',
            'Diknis Deteksi Dini / intelegen',
            'Diknis Deteksi dini',
            'Diknis Manajemen Kearsipan',
            'Diknis Pelayanan Adminis terpadu kecamatan',
            'Diknis Pendg.sertf organik tan.pangan',
            'Diknis Penerapan Konvensi Hak anak',
            'Diknis Pengadaan Barang/jasa utk PPTK - ANGK.1',
            'Diknis Pengadaan Barang/jasa utk PPTK - ANGK.2',
            'Diknis Pengadaan Barang/jasa utk PPTK - ANGK.3',
            'Diknis Pengadaan Barang/jasa utk PPTK - ANGK.4',
            'Diknis Pengelolaan Aset Angkt.1',
            'Diknis Pengelolaan Aset l - ANGK.1',
            'Diknis Pengelolaan Aset ll - ANGK.2',
            'Diknis Pengelolaan Keuangan Desa Angkt.1',
            'Diknis Pengelolaan Perijinan Bangunan Angkt.1',
            'Diknis Pengelolaan Perpustakaan',
            'Diknis Pengelolaan Persampahan Angkt.1',
            'Diknis Pengawas Jalan Angkt.1',
            'Diknis Pengawasan Sekolah SMA-SMK',
            'Diknis Perancang Perpu Angkt.1',
            'Diknis Perancang Perundang - undangan l - ANGK.1',
            'Diknis Perancang Perundang - undangan ll - ANGK.2',
            'Diknis Perbendaharaan Angkt.1',
            'Diknis Perencanaan dan Penganggaran (plan',
            'Diknis Perencanaan dan Penganggaran l - ANGK.1',
            'Diknis Perencanaan dan Penganggaran lI - ANGK.2',
            'Diknis Perencanaan Penanggulangan Bencana Angkt.1',
            'Diknis Perencanaan Pembangunan Daerah Angkt.1',
            'Diknis Perancanaan Pembangunan ll - ANGK.2',
            'Diknis Penyuluh Berbasis Audio Visual',
            'Diknis Penyusunan dok.Akreditasi Puskesmas Angk.1',
            'Diknis Pranata Humas l - ANGK.1',
            'Diknis Pranata Humas ll - ANGK.2',
            'Diknis Rekam Medis bagi Petugas R.M Puskesmas Angkt.1',
            'Diknis Resi Gudang Angkt.1',
            'Diknis Review Lap Keuangan Angkt.1',
            'Diknis SAKIP I - ANGK.1',
            'Diknis SAKIP Il - ANGK.2',
            'Dikjabfungs bidan angk.1',
            'Dikjabfungs Penyuluh Kes Masy jenjang Ahli Angkt.1',
            'Dikjabfungs sanitarian jenjang ahli',
            'DT Dasar Satpol PP Pola 150 Jam - Angk.1',
            'DT Dasar Satpol PP Pola 150 Jam - Angk.2',
            'DT Dasar Satpol PP Pola 150 Jam - Angk.3',
            'DT Pengadaan Barang Jasa bagi PPK - ANGK.1',
            'GTA - Business Process Engonering (bekerja sama dengan Kementerian Kominfo)',
            'GTA - Digital Public Relation (bekerja sama dengan Kementerian Kominfo)',
            'GTA - Fasilitator Pembelajaran Digital',
            'GTA - Manajemen Resiko SPBE (bekerja sama dengan Kementerian Kominfo)',
            'GTA - Social Media Analytics',
            'IMPLEMENTASI PEMBELAJARAN BERPUSAT KEPADA PESERTA DIDIK BAGI GURU ANGKATAN 1',
            'IMPLEMENTASI PEMBELAJARAN BERPUSAT KEPADA PESERTA DIDIK BAGI GURU ANGKATAN 2',
            'IMPLEMENTASI PEMBELAJARAN BERPUSAT KEPADA PESERTA DIDIK BAGI GURU ANGKATAN 3',
            'IMPLEMENTASI PEMBELAJARAN BERPUSAT KEPADA PESERTA DIDIK BAGI GURU ANGKATAN 4',
            'IMPLEMENTASI PEMBELAJARAN BERPUSAT KEPADA PESERTA DIDIK BAGI GURU ANGKATAN 5',
            'K1/K2',
            'Latsar CPNS Angkatan 3 Pemkot Surakarta',
            'Latsar CPNS Angkatan CXVII (Mandiri 3) Pemkab Kudus',
            'Latsar CPNS Angkatan I Pemkab Pemalang',
            'Latsar CPNS Angkatan II Pemkab Pemalang',
            'Latsar CPNS Angkatan III Pemkab Pemalang',
            'Latsar CPNS Angkatan IX Pemkab Boyolali',
            'Latsar CPNS Angkatan X Pemkab Boyolali',
            'Latsar CPNS Angkatan XI Pemkab Boyolali',
            'Latsar CPNS Angkatan XLI (Mandiri 2) Pemkab Kudus',
            'Latsar CPNS Angkatan XXX Pemkab Kudus',
            'Latsar CPNS Angkatan XXXVII (Mandiri 1) Pemkab Kudus',
            'Latsar CPNS Gelombang III Golongan 2 Angk. I Pemkot Surakarta',
            'Latsar CPNS Gelombang III Golongan 2 Angk. II Pemkot Surakarta',
            'Latsar CPNS Gelombang III Golongan 3 Angk. I Pemkot Surakarta',
            'Latsar CPNS Gelombang III Golongan 3 Angk. II Pemkot Surakarta',
            'Latsar CPNS Gelombang III Golongan 3 Angk. II Pemkot Surakarta',
            'Latsar CPNS Gol. II Angkatan XXXI Pemkab Sragen',
            'Latsar CPNS Gol. II Angkatan XXXVI Kab. Sragen',
            'Latsar CPNS Gol. II Angkatan LXXIII Kab. Blora',
            'Latsar CPNS Gol. II Angkatan XVI Kab. Boyolali',
            'Latsar CPNS Gol. II Angkatan XVII Pemkab Boyolali',
            'Latsar CPNS Gol. II Angkatan XX Kab. Cilacap',
            'Latsar CPNS Gol. II Angkatan XXXIII Kab. Kudus',
            'Latsar CPNS Gol. II Pemkot Semarang Angkatan XXVIII',
            'Latsar CPNS Gol. II Pemkot Semarang Angkatan XXIX',
            'Latsar CPNS Gol. III Angk. VII Kab. Jepara',
            'Latsar CPNS Gol. III Angkatan 5',
            'Latsar CPNS Gol. III Angkatan 6',
            'Latsar CPNS Gol. III Angkatan XVIII',
            'Latsar CPNS Gol. III Angkatan XXI Kab. Banyumas',
            'Latsar CPNS Gol. III Angkatan XXII Kab. Banyumas',
            'Latsar CPNS Gol. III Angkatan XXIII Kab. Demak',
            'Latsar CPNS Gol. III Angkatan XXIII Pemkab Demak',
            'Latsar CPNS Gol. III Angkatan XXIV Pemkab Demak',
            'Latsar CPNS Gol. III Angkatan XXV Pemkab Wonogiri',
            'Latsar CPNS Gol. III Angkatan XXVI Pemkab Wonogiri',
            'Latsar CPNS Gol. III Angkatan XXVIII Pemkab Boyolali',
            'Latsar CPNS Gol. III Angkatan XXXII Kab. Boyolali',
            'Latsar CPNS Gol. III Angkatan XXXIV Balatkop',
            'Latsar CPNS Gol. III Angkatan XXXIX DMadinah Sukoharjo',
            'Latsar CPNS Gol. III Angkatan XXXV DMadinah Solo',
            'Latsar CPNS Gol. III Angkatan XXXVII DMadinah Solo',
            'Latsar CPNS Gol. III Angkatan XXXVIII PTT Migas',
            'Latsar CPNS Gol. III Angkatan XL PTT Migas',
            'Latsar CPNS Gol. III Angkatan XLI Kota Surakarta',
            'Latsar CPNS Gol. III Angkatan XLIII DMadinah Sukoharjo',
            'Latsar CPNS Gol. III Angkatan XIX Kab. Cilacap',
            'Latsar CPNS Gol. III Kab. Banyumas Angkatan I',
            'Latsar CPNS Gol. III Kab. Banyumas Angkatan II',
            'Latsar CPNS Gol. III Kab. Cilacap Angkatan I',
            'Latsar CPNS Gol. III Kab. Jepara Angkatan IX',
            'Latsar CPNS Gol. III Kab. Rembang Angkatan VIII',
            'Latsar CPNS Gol. III Kab. Rembang Angkatan XII',
            'Latsar CPNS Gol. III Kab. Rembang Angkatan XIII',
            'Latsar CPNS Gol. III Kab. Sukoharjo Angkatan X',
            'Latsar CPNS Gol. III Kab. Sukoharjo Angkatan XI',
            'Latsar CPNS Gol. III Kab. Tegal Angkatan 5',
            'Latsar CPNS Gol. III Kab. Tegal Angkatan 6',
            'Latsar CPNS Gol. III Pemkab Batang Periode 17 Juni s/d 15 Agustus 2019 di Sumbing',
            'Latsar CPNS Gol. III Pemkab Batang Periode 17 Juni s/d 21 Agustus 2019 di Balatkop',
            'Latsar CPNS Gol. III Pemkab Batang Periode 24 Juni s/d 31 Agustus 2019 di Balatkop',
            'Latsar CPNS Gol. III Pemkab Batang Periode 5 Agustus s/d 9 Oktober 2019 di BALATKOP',
            'Latsar CPNS Gol. III Pemkab Batang Periode 12 Agustus s/d 16 Oktober 2019 di Balatkop',
            'Latsar CPNS Gol. III Pemkab Blora Periode 20 Juni s/d 28 Agustus 2019 di PTT Migas Cepu',
            'Latsar CPNS Gol. III Pemkab Blora Periode 24 Juli s/d 27 September 2019 di PTT Migas Cepu',
            'Latsar CPNS Gol. III Pemkab Blora Periode 26 Agustus s/d 25 Oktober 2019 di PTT Migas Cepu',
            'Latsar CPNS Gol. III Pemkab Blora Periode 29 Juli s/d 2 Oktober 2019 di PTT Migas Cepu',
            'Latsar CPNS Gol. III Pemkab Brebes Periode 18 Juni s/d 21 Agustus 2019 di Sumbing',
            'Latsar CPNS Gol. III Pemkab Grobogan periode 16 Juli s.d 14 September 2019 di BKK Supriyadi',
            'Latsar CPNS Gol. III Pemkab Grobogan Periode 25 Juni s/d 28 Agustus 2019 di BKK Supriyadi',
            'Latsar CPNS Gol. III Pemkab Grobogan Periode 31 Juli s/d 2 Oktober 2019 di BKK Supriyadi',
            'Latsar CPNS Gol. III Pemkab Karanganyar Periode 26 Agustus s/d 23 Oktober 2019 di BPSDM Nak',
            'Latsar CPNS Gol. III Pemkab Karanganyar Periode 3 September s/d 2 November 2019 di Sragen',
            'Latsar CPNS Gol. III Pemkab Karanganyar Periode 3 September s/d 13 November 2019 di DMadinah Solo',
            'Latsar CPNS Gol. III Pemkab Karanganyar Periode 5 Agustus s/d 9 Oktober 2019 di Sragen',
            'Latsar CPNS Gol. III Pemkab Karanganyar Periode 14 Oktober s/d 14 Desember 2019 di Sragen',
            'Latsar CPNS Gol. III Pemkab Kebumen dan Sragen Periode 8 Oktober s/d 7 Desember 2019 di DMadinah Solo',
            'Latsar CPNS Gol. III Pemkab Kebumen Periode 24 Juni s/d 28 Agustus 2019 di BPSDM Nak Ungaran',
            'Latsar CPNS Gol. III Pemkab Kebumen Periode 29 Juli s/d 28 September 2019 di BPSDM Nak',
            'Latsar CPNS Gol. III Pemkab Kebumen Periode 2 September s/d 6 November 2019 di DMadinah Solo',
            'Latsar CPNS Gol. III Pemkab Klaten Periode 19 Juni s/d 29 Agustus 2019 di DMadinah Sukoharjo',
            'Latsar CPNS Gol. III Pemkab Klaten Periode 22 Juli s/d 21 September 2019 di Dmadinah Solo',
            'Latsar CPNS Gol. III Pemkab Klaten Periode 23 Juli s/d 25 September 2019 di Dmadinah Solo',
            'Latsar CPNS Gol. III Pemkab Klaten Periode 3 September s/d 2 November 2019 di BPSMD Nak',
            'Latsar CPNS Gol. III Pemkab Klaten Periode 5 September s/d 6 November 2019 di BPSMD Nak',
            'Latsar CPNS Gol. III Pemkab Klaten Periode 5 September s/d 15 November 2019 di DMadinah Sukoharjo',
            'Latsar CPNS Gol. III Pemkab Klaten Periode 7 Oktober s/d 5 Desember 2019 di DMadinah Solo',
            'Latsar CPNS Gol. III Pemkab Klaten Periode 9 Oktober s/d 11 Desember 2019 di DMadinah Sukoharjo',
            'Latsar CPNS Gol. III Pemkab Klaten Periode 10 Oktober s/d 12 Desember 2019 di DMadinah Sukoharjo',
            'Latsar CPNS Gol. III Pemkab Pati Periode 20 Mei s/d 31 Juli 2019 di BKK Supriyadi',
            'Latsar CPNS Gol. III Pemkab Pati Periode 22 Juli s/d 21 September 2019 di BKK Supriyadi',
            'Latsar CPNS Gol. III Pemkab Pati Periode 22 Juli s/d 21 September 2019 di PTT Migas Cepu',
            'Latsar CPNS Gol. III Pemkab Pati Periode 26 Agustus s/d 23 Oktober 2019 di BKK Supriyadi',
            'Latsar CPNS Gol. III Pemkab Pati Periode 26 Juni s/d 29 Agustus 2019 di BKK Supriyadi',
            'Latsar CPNS Gol. III Pemkab Pati Periode 2 September s/d 31 Oktober 2019 di BKK Supriyadi',
            'Latsar CPNS Gol. III Pemkab Pati Periode 2 September s/d 31 Oktober 2019 di PTT Migas Cepu',
            'Latsar CPNS Gol. III Pemkab Pati Periode 31 Juli s/d 2 Oktober 2019 di BKK Supriyadi',
            'Latsar CPNS Gol. III Pemkab Pekalongan Periode 25 Juni s/d 28 Agustus 2019 di PKK Ungaran',
            'Latsar CPNS Gol. III Pemkab Pekalongan Periode 24 September s/d 23 November 2019 di PKK Ungaran',
            'Latsar CPNS Gol. III Pemkab Purbalingga Periode 16 Mei s/d 27 Juli 2019 di BPSDM Nak Ungaran',
            'Latsar CPNS Gol. III Pemkab Purbalingga Periode 20 Juni s/d 24 Agustus 2019 di BPSDM Nak Ungaran',
            'Latsar CPNS Gol. III Pemkab Purbalingga Periode 26 Juni s/d 29 Agustus 2019 di BPSDM Nak Ungaran',
            'Latsar CPNS Gol. III Pemkab Purbalingga Periode 31 Juli s/d 2 Oktober 2019 di BPSDM Nak',
            'Latsar CPNS Gol. III Pemkab Purworejo Periode 24 Juli s/d 27 September 2019 di DMadinah Sukoharjo',
            'Latsar CPNS Gol. III Pemkab Purworejo Periode 31 Juli s/d 2 Oktober 2019 di Soropadan',
            'Latsar CPNS Gol. III Pemkab Purworejo Periode 30 September s/d 28 November 2019 di Soropadan',
            'Latsar CPNS Gol. III Pemkab Rembang Periode 19 Juni s/d 24 Agustus 2019 di PTT Migas Cepu',
            'Latsar CPNS Gol. III Pemkab Semarang Periode 15 Juli s/d 19 September 2019 di PKK UNGARAN',
            'Latsar CPNS Gol. III Pemkab Semarang Periode 19 Juni s/d 21 Agustus 2019 di PKK Ungaran',
            'Latsar CPNS Gol. III Pemkab Semarang Periode 22 Juli s/d 28 September 2019 di PKK Ungaran',
            'Latsar CPNS Gol. III Pemkab Sragen Periode 17 Juni s/d 24 Agustus 2019 di DMadinah Solo',
            'Latsar CPNS Gol. III Pemkab Sragen Periode 18 Juni s/d 28 Agustus 2019 di DMadinah Solo',
            'Latsar CPNS Gol. III Pemkab Sragen Periode 23 Juli s/d 26 September 2019 di DMadinah Sukoharjo',
            'Latsar CPNS Gol. III Pemkab Sragen Periode 26 Agustus s/d 26 Oktober 2019 di Sragen',
            'Latsar CPNS Gol. III Pemkab Sragen Periode 30 Juli s/d 2 Oktober 2019 di Sragen',
            'Latsar CPNS Gol. III Pemkab Sragen Periode 4 September s/d 14 November 2019 di DMadinah Sukoharjo',
            'Latsar CPNS Gol. III Pemkab Sragen Periode 8 Oktober s/d 13 Desember 2019 di Sragen',
            'Latsar CPNS Gol. III Pemkab Tegal Periode 1 Oktober s/d 7 Desember 2019 di Balatkop',
            'Latsar CPNS Gol. III Pemkab Wonosobo Periode 13 Mei s/d 24 Juli 2019 di BPSDM Nak Ungaran',
            'Latsar CPNS Gol. III Pemkab Wonosobo Periode 30 Juli s/d 28 September 2019 di Soropadan',
            'Latsar CPNS Gol. III Pemkab Wonosobo Periode 6 Agustus s/d 5 Oktober 2019 di BLPP Soropadan',
            'Latsar CPNS Gol. III Pemkab Wonosobo dan Sukoharjo Periode 9 Oktober s/d 11 Desember 2019 di BPSDM Nak',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 1',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 10',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 11',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 12',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 13',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 14',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 2',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 3',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 4',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 5',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 6',
            'Latsar CPNS Gol. III Pemkot Semarang Angkatan 9',
            'Latsar CPNS Gol. III/II Angkatan 102 Periode 30 Juni s.d. 18 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 103 Periode 30 Juni s.d. 18 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 104 Periode 30 Juni s.d. 18 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 105 Periode 30 Juni s.d. 18 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 110 Periode 5 Juli s.d. 25 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 111 Periode 5 Juli s.d. 25 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 112 Periode 5 Juli s.d. 25 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 113 Periode 5 Juli s.d. 25 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 118 Periode 12 Juli s.d. 02 Oktober 2021',
            'Latsar CPNS Gol. III/II Angkatan 119 Periode 12 Juli s.d. 02 Oktober 2021',
            'Latsar CPNS Gol. III/II Angkatan 120 Periode 12 Juli s.d. 02 Oktober 2021',
            'Latsar CPNS Gol. III/II Angkatan 121 Periode 12 Juli s.d. 02 Oktober 2021',
            'Latsar CPNS Gol. III/II Angkatan 132 Periode 2 Agustus s.d. 16 Oktober 2021',
            'Latsar CPNS Gol. III/II Angkatan 133 Periode 2 Agustus s.d. 16 Oktober 2021',
            'Latsar CPNS Gol. III/II Angkatan 134 Periode 2 Agustus s.d. 16 Oktober 2021',
            'Latsar CPNS Gol. III/II Angkatan 139 Periode 11 Agustus s.d. 30 Oktober 2021',
            'Latsar CPNS Gol. III/II Angkatan 140 Periode 11 Agustus s.d. 30 Oktober 2021',
            'Latsar CPNS Gol. III/II Angkatan 141 Periode 11 Agustus s.d. 30 Oktober 2021',
            'Latsar CPNS Gol. III/II Angkatan 159 Periode 14 September s.d. 27 November 2021',
            'Latsar CPNS Gol. III/II Angkatan 160 Periode 14 September s.d. 27 November 2021',
            'Latsar CPNS Gol. III/II Angkatan 161 Periode 14 September s.d. 27 November 2021',
            'Latsar CPNS Gol. III/II Angkatan 165 Periode 21 September s.d. 4 Desember 2021',
            'Latsar CPNS Gol. III/II Angkatan 166 Periode 21 September s.d. 4 Desember 2021',
            'Latsar CPNS Gol. III/II Angkatan 167 Periode 21 September s.d. 4 Desember 2021',
            'Latsar CPNS Gol. III/II Angkatan 168 Periode 21 September s.d. 4 Desember 2021',
            'Latsar CPNS Gol. III/II Angkatan 169 Periode 27 September s.d. 11 Desember 2021',
            'Latsar CPNS Gol. III/II Angkatan 170 Periode 27 September s.d. 11 Desember 2021',
            'Latsar CPNS Gol. III/II Angkatan 171 Periode 27 September s.d. 11 Desember 2021',
            'Latsar CPNS Gol. III/II Angkatan 172 Periode 27 September s.d. 11 Desember 2021',
            'Latsar CPNS Gol. III/II Angkatan 32 Periode 5 April s.d. 3 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 33 Periode 5 April s.d. 3 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 34 Periode 5 April s.d. 3 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 35 Periode 5 April s.d. 3 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 37 Periode 8 April s.d. 10 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 38 Periode 8 April s.d. 10 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 39 Periode 8 April s.d. 10 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 40 Periode 8 April s.d. 10 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 45 Periode 12 April s.d. 17 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 46 Periode 12 April s.d. 17 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 47 Periode 12 April s.d. 17 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 48 Periode 12 April s.d. 17 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 52 Periode 19 April s.d. 31 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 53 Periode 19 April s.d. 31 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 54 Periode 19 April s.d. 31 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 55 Periode 19 April s.d. 31 Juli 2021',
            'Latsar CPNS Gol. III/II Angkatan 64 Periode 24 Mei s.d. 7 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 65 Periode 24 Mei s.d. 7 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 66 Periode 24 Mei s.d. 7 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 67 Periode 24 Mei s.d. 7 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 72 Periode 27 Mei s.d. 16 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 73 Periode 27 Mei s.d. 16 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 74 Periode 27 Mei s.d. 16 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 75 Periode 27 Mei s.d. 16 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 77 Periode 2 Juni s.d. 28 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 78 Periode 2 Juni s.d. 28 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 79 Periode 2 Juni s.d. 28 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 80 Periode 2 Juni s.d. 28 Agustus 2021',
            'Latsar CPNS Gol. III/II Angkatan 82 Periode 7 Juni s.d. 4 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 83 Periode 7 Juni s.d. 4 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 84 Periode 7 Juni s.d. 4 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 85 Periode 7 Juni s.d. 4 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 94 Periode 28 Juni s.d. 11 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 95 Periode 28 Juni s.d. 11 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 96 Periode 28 Juni s.d. 11 September 2021',
            'Latsar CPNS Gol. III/II Angkatan 97 Periode 28 Juni s.d. 11 September 2021',
            'Latsar CPNS Gol. III/II Gelombang 1 Periode I 1 Maret s.d. 22 Mei 2021',
            'Latsar CPNS Gol. III/II Gelombang 1 Periode I 1 Maret s.d. 31 Mei 2021',
            'Latsar CPNS Gol. III/II Gelombang 1 Periode II 1 Maret s.d. 31 Mei 2021',
            'Latsar CPNS Gol. III/II Gelombang 1 Periode III 1 Maret s.d. 31 Mei 2021',
            'Latsar CPNS Gol. III/II Gelombang 1 Periode IV 1 Maret s.d. 31 Mei 2021',
            'Latsar CPNS Gol. III/II Gelombang 2 Periode I 3 Maret s.d. 4 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 2 Periode II 3 Maret s.d. 4 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 2 Periode III 3 Maret s.d. 4 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 2 Periode IV 3 Maret s.d. 4 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 3 Periode I 8 Maret s.d. 9 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 3 Periode II 8 Maret s.d. 9 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 3 Periode III 8 Maret s.d. 9 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 3 Periode IV 8 Maret s.d. 9 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 4 Periode I 10 Maret s.d. 12 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 4 Periode II 10 Maret s.d. 12 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 4 Periode III 10 Maret s.d. 12 Juni 2021',
            'Latsar CPNS Gol. III/II Gelombang 4 Periode IV 10 Maret s.d. 12 Juni 2021',
            'Latsar CPNS Gol. III/II Periode 13 Mei s/d 26 Juli 2019',
            'Latsar CPNS Gol. III/II Periode 14 September s.d. 27 November 2021',
            'Latsar CPNS Gol. III/II Periode 15 Mei s/d 1 Agustus 2019',
            'Latsar CPNS Gol. III/II Periode 17 Juni s/d 21 Agustus 2019',
            'Latsar CPNS Gol. III/II Periode 18 Juni s/d 22 Agustus 2019',
            'Latsar CPNS Gol. III/II Periode 19 Juni s/d 23 Agustus 2019',
            'Latsar CPNS Gol. III/II Periode 21 September s.d. 4 Desember 2021',
            'Latsar CPNS Gol. III/II Periode 22 Juli s/d 2 Oktober 2019',
            'Latsar CPNS Gol. III/II Periode 23 Juli s/d 26 September 2019',
            'Latsar CPNS Gol. III/II Periode 24 Juli s/d 27 September 2019',
            'Latsar CPNS Gol. III/II Periode 24 Juni s/d 28 Agustus 2019',
            'Latsar CPNS Gol. III/II Periode 26 Agustus s/d 30 Oktober 2019',
            'Latsar CPNS Gol. III/II Periode 26 Juni s/d 30 Agustus 2019',
            'Latsar CPNS Gol. III/II Periode 27 Agustus s/d 31 Oktober 2019',
            'Latsar CPNS Gol. III/II Periode 27 September s.d. 11 Desember 2021',
            'Latsar CPNS Gol. III/II Periode 28 Agustus s/d 1 November 2019',
            'Latsar CPNS Gol. III/II Periode 29 Juli s/d 2 Oktober 2019',
            'Latsar CPNS Gol. III/II Periode 3 September s/d 6 November 2019',
            'Latsar CPNS Gol. III/II Periode 4 September s/d 7 November 2019',
            'Latsar CPNS Gol. III/II Periode 5 Agustus s/d 16 Oktober 2019',
            'Latsar CPNS Gol. III/II Periode 7 Mei s/d 19 Juli 2019',
            'Latsar CPNS Gol. III/II Periode 9 Mei s/d 24 Juli 2019',
            'Latsar CPNS Gol. III/II Periode 10 September s/d 13 November 2019',
            'Latsar CPNS Gol. III/II Periode 1 Oktober s/d 4 Desember 2019',
            'Latsar CPNS Gol. III/II Periode 2 Oktober s/d 5 Desember 2019',
            'Latsar CPNS Gol. III/II Periode 7 Oktober s/d 18 Desember 2019',
            'Latsar CPNS Gol. III/II Periode 8 Oktober s/d 11 Desember 2019',
            'Latsar CPNS Gol. III Periode 2 Mei s/d 17 Juli 2019',
            'Latsar CPNS Gol.III BIP Pemkab Sragen periode 18 Juli s.d 25 September di Sumbing',
            'Latsar CPNS Gol.III BIP Pemkot Tegal Periode 15 Juli s/d 21 September 2019 di Sumbing BPSDMD',
            'Latsar CPNS Gol.II BIP Pemkot Salatiga periode 10 Juli s.d 18 September 2019 di Sumbing BPSDMD blm fix',
            'Latsar CPNS Gol.II BIP Pemkot Salatiga Periode 10 Juli s/d 18 September 2019 di Sumbing BPSDMD',
            'Latsar CPNS Gol.II BIP Periode 26 Agustus s/d 25 Oktober 2019 di Sumbing',
            'Latsar CPNS Gol.II BIP Periode 27 Agustus s/d 26 Oktober 2019 di Sumbing',
            'Latsar CPNS Gol.II Pemkot Tegal, Pemkab Jepara dan Pekalongan Periode 1 Oktober s/d 30 November 2019 di Sumbing',
            'Latsar CPNS Periode 13 Mei s/d 24 Juli 2019 Pemkab Purbalingga di Sumbing',
            'Latsar CPNS Periode 14 Mei s/d 25 Juli 2019 Pemkab Jepara di Sumbing',
            'Latsar CPNS Periode 16 Mei s/d 27 Juli 2019 Pemkab Wonosobo di Sumbing',
            'Lat Prajab CPNS Gol III/II dari Tenaga Non Honorer K2 BIP Angk. 23 Periode 17 s.d 25 September BPSDMD Prov. Jateng',
            'Lat Prajab CPNS Gol III/II dari Tenaga Non Honorer K2 BIP Angk. 24 Periode 17 s.d 25 September BPSDMD Prov. Jateng',
            'Lat Prajab CPNS Gol III/II dari Tenaga Non Honorer K2 BIP Angk. I Periode 13 s.d 21 Mei BPSDMD Prov. Jateng',
            'Lat Prajab CPNS Gol III/II dari Tenaga Non Honorer K2 BIP Angk. II Periode 13 s.d 21 Mei BPSDMD Prov. Jateng',
            'Lat Prajab CPNS Gol III/II dari Tenaga Non Honorer K2 BIP Angk. III Periode 20 s.d 28 Mei BPSDMD Prov. Jateng',
            'Lat Prajab CPNS Gol III/II dari Tenaga Non Honorer K2 BIP Angk. IV Periode 20 s.d 28 Mei BPSDMD Prov. Jateng',
            'Lat Prajab CPNS Gol III/II dari Tenaga Non Honorer K2 BIP Angk. V Periode 3 s.d 11 Juli BPSDMD Prov. Jateng',
            'Lat Prajab CPNS Gol III/II dari Tenaga Non Honorer K2 BIP Angk. VI Periode 15 s.d 23 Juli BPSDMD Prov. Jateng',
            'Lat Prajab CPNS Gol III/II dari Tenaga Non Honorer K2 BIP Angk. VII Periode 30 Juli s.d 7 Agustus BPSDMD Prov. Jateng',
            'Lat Prajab CPNS Gol III/II dari Tenaga Non Honorer K2 BIP Periode 27 Agustus s.d 4 September BPSDMD Prov. Jateng',
            'Local Goverment Leadership Training Angkatan I',
            'Local Goverment Leadership Training Angkatan II',
            'Local Goverment Leadership Training Angkatan III',
            'Local Goverment Leadership Training Angkatan IV',
            'Local Government Leadership Training (LGLT)',
            'Local Government Leadership Training Angkatan VI',
            'Local Government Leadership Training Periode 26 Jan s.d 18 Feb',
            'Manunggal Leadership Retreat Untuk Ngopeni Nglakoni Jawa Tengah',
            'MOOC Peningkatan Kompetensi Pedagogik bagi Guru SMA, SMK, dan SLB',
            'MOOC Tematik English for ASN',
            'MOOC Tematik Pendidikan Anti Korupsi',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 1',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 10',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 11',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 12',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 2',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 3',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 4',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 5',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 6',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 7',
            'Orientasi Anggota DPRD Kab/Kota Prov Jateng Angk. 8',
            'Orientasi Anggota DPRD Tahap I (Angkatan I)',
            'Orientasi Anggota DPRD Tahap I (Angkatan II)',
            'Orientasi Anggota DPRD Tahap I (Angkatan III)',
            'Orientasi Anggota DPRD Tahap I (Angkatan IV)',
            'Orientasi Anggota DPRD Tahap II (Angkatan V)',
            'Orientasi Anggota DPRD Tahap II (Angkatan VI)',
            'Orientasi Anggota DPRD Tahap II (Angkatan VII)',
            'Orientasi Anggota DPRD Tahap II (Angkatan VIII)',
            'Orientasi Anggota DPRD Tahap III (Angkatan IX)',
            'Orientasi Anggota DPRD Tahap III (Angkatan X)',
            'Orientasi Anggota DPRD Tahap III (Angkatan XI)',
            'Orientasi Anggota DPRD Tahap III (Angkatan XII)',
            'Orientasi Anggota DPRD Tahap IV (Angkatan XIII)',
            'Orientasi Anggota DPRD Tahap IV (Angkatan XIV)',
            'Orientasi Anggota DPRD Tahap IV (Angkatan XV)',
            'Orientasi Anggota DPRD Tahap IV (Angkatan XVI)',
            'Orientasi Anggota DPRD Tahap IX (Angkatan XXXIII)',
            'Orientasi Anggota DPRD Tahap IX (Angkatan XXXIV)',
            'Orientasi Anggota DPRD Tahap IX (Angkatan XXXV)',
            'Orientasi Anggota DPRD Tahap V (Angkatan XVII)',
            'Orientasi Anggota DPRD Tahap V (Angkatan XVIII)',
            'Orientasi Anggota DPRD Tahap V (Angkatan XIX)',
            'Orientasi Anggota DPRD Tahap V (Angkatan XX)',
            'Orientasi Anggota DPRD Tahap VI (Angkatan XXI)',
            'Orientasi Anggota DPRD Tahap VI (Angkatan XXII)',
            'Orientasi Anggota DPRD Tahap VI (Angkatan XXIII)',
            'Orientasi Anggota DPRD Tahap VI (Angkatan XXIV)',
            'Orientasi Anggota DPRD Tahap VII (Angkatan XXV)',
            'Orientasi Anggota DPRD Tahap VII (Angkatan XXVI)',
            'Orientasi Anggota DPRD Tahap VII (Angkatan XXVII)',
            'Orientasi Anggota DPRD Tahap VII (Angkatan XXVIII)',
            'Orientasi Anggota DPRD Tahap VIII (Angkatan XXIX)',
            'Orientasi Anggota DPRD Tahap VIII (Angkatan XXX)',
            'Orientasi Anggota DPRD Tahap VIII (Angkatan XXXI)',
            'Orientasi Anggota DPRD Tahap VIII (Angkatan XXXII)',
            'Orientasi Bagi Calon Pegawai Tetap Non ASN Pola Swakelola Universitas Negeri Semarang',
            'Orientasi Pegawai Tetap Non ASN Universitas Tidar Tahun 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Angk. 1 - 5 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Angk. 11 - 15 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Angk. 16 - 20 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Angk. 21 - 25 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Angk. 26 - 29 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Angk. 30 - 34 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Angk. 35 - 38 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Angk. 39 - 45 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Angk. 6 - 10 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kab. Brebes Angkatan 1 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kab. Brebes Angkatan 2 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kab. Brebes Angkatan 3 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kab. Brebes Angkatan 4 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kab. Brebes Angkatan 5 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kab. Brebes Angkatan 6 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 1',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 10',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 11',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 12',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 13',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 14',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 15',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 16',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 17',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 18',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 19',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 2',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 20',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 21',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 22',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 3',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 4',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 5',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 6',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 7',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 8',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Blora Angkatan 9',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Angk. 94 Tahun 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerjasama Angkatan II Periode 10 s.d. 14 Oktober 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerjasama Angkatan III Periode 17 s.d. 21 Oktober 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerjasama Angkatan IV Periode 24 s.d. 28 Oktober 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerjasama Angkatan V Periode 31 Oktober s.d. 4 November 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan 1 Periode 21 s.d. 25 Agustus 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan VI Periode 19 s.d. 23 Agustus 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan VII Periode 26 s.d. 30 Agustus 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan VIII Periode 2 s.d. 6 September 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan XI Periode 30 September s.d. 4 Oktober 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan XII Periode 7 s.d. 11 Oktober 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan XIII Periode 14 s.d. 18 Oktober 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan XIV Periode 21 s.d. 25 Oktober 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan XV Periode 28 Oktober s.d. 1 November 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan XVI Periode  4 s.d. 8 November 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan XVII Periode  11 s.d. 15 November 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan IX Periode 9 s.d. 13 September 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Kudus Pola Kerja Sama Angkatan X Periode 23 s.d. 27 September 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Pemalang Angk. 18 - 22 Tahun 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Pemalang Angk. 23 - 27 Tahun 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Pemalang Angk. 28 - 32 Tahun 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Pemalang Angk. 33 - 37 Tahun 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Pemalang Angk. 89 - 93 Tahun 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 11 s.d. 12 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 13 s.d. 16 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 17 s.d. 20 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 21 s.d. 24 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 25 s.d. 28 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 29 s.d. 32 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 57 â€“ 60 Tahun 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 6 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 61 â€“ 65 Tahun 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 66 â€“ 70 Tahun 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 7 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 71 â€“ 75 Tahun 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 74 - 78 Tahun 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 76 â€“ 80 Tahun 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 79 - 83 Tahun 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 8 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 84 - 88 Tahun 2022',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Semarang Angk. 9 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Sukoharjo Angkatan ke-1 Periode 15 s.d. 17 Februari 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Sukoharjo Angkatan ke-2 Periode 22 s.d. 24 Februari 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Sukoharjo Angkatan ke-3 Periode 29 s.d. 31 Januari 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Sukoharjo Angkatan ke-4 Periode 5 s.d. 7 Februari 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Sukoharjo Angkatan ke-5 Periode 12 s.d. 15 Februari 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Sukoharjo Angkatan ke-6 Periode 19 s.d. 21 Februari 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Sukoharjo Angkatan ke-7 Periode 26 s.d. 28 Februari 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kabupaten Sukoharjo Angkatan ke-8 Periode 4 s.d. 6 Maret 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kota Magelang Angk. 1 Tahun 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kota Magelang Angk. 2 Tahun 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kota Magelang Angk. 3 Tahun 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kota Magelang Angk. 4 Tahun 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Kota Magelang Angk. 5 Tahun 2024',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angk. 1 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angk. 2 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angk. 3 s.d. 4 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angk. 46 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angk. 47 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angk. 5 s.d. 6 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angk. 7 s.d. 8 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angk. 9 s.d. 10 Tahun 2025',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angkatan 48 - 52 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angkatan 53 - 57 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angkatan 58 - 62 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angkatan 63 - 67 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angkatan 68 - 72 Tahun 2023',
            'Orientasi Pengenalan Nilai dan Etika Instansi Pemerintah bagi PPPK Provinsi Jawa Tengah Angkatan 73 - 77 Tahun 2023',
            'PELATIHAN FUNGSIONAL ANALIS SDM APARATUR ANGKATAN I',
            'PELATIHAN FUNGSIONAL ANALIS SDM APARATUR ANGKATAN II',
            'PELATIHAN JABATAN FUNGSIONAL ANALIS SDM APARATUR',
            'PELATIHAN JABATAN FUNGSIONAL PEKERJA SOSIAL JENJANG AHLI PERTAMA',
            'PELATIHAN JABATAN FUNGSIONAL PERAWAT PENGANGKATAN PERTAMA',
            'PELATIHAN JABATAN FUNGSIONAL PERAWAT PENGANGKATAN PERTAMA ANGKATAN II',
            'PELATIHAN KHUSUS ANALIS KEBIJAKAN ANGKATAN IX',
            'PELATIHAN KHUSUS ANALIS KEBIJAKAN ANGKATAN V',
            'PELATIHAN KHUSUS ANALIS KEBIJAKAN ANGKATAN VI',
            'PELATIHAN KHUSUS ANALIS KEBIJAKAN ANGKATAN VII',
            'PELATIHAN KHUSUS ANALIS KEBIJAKAN ANGKATAN VIII',
            'PELATIHAN KHUSUS ANALIS KEBIJAKAN ANGKATAN X',
            'PELATIHAN MANAJEMEN KEPALA SEKOLAH',
            'PELATIHAN MANAJEMEN KEPALA SEKOLAH ( BIP )',
            'PELATIHAN MANAJEMEN KEPALA SEKOLAH ANGKATAN II',
            'PELATIHAN MANAJEMEN KEPALA SEKOLAH JENJANG SMA / SMK / SLB',
            'PELATIHAN MANAJEMEN PUSKESMAS ANGKATAN III TAHUN 2025',
            'PELATIHAN MANAJEMEN PUSKESMAS ANGKATAN IV TAHUN 2025',
            'PELATIHAN MANAJEMEN PUSKESMAS INTEGRASI LAYANAN PRIMER ( ILP ) ANGKATAN II',
            'PELATIHAN MANAJEMEN PUSKESMAS INTEGRASI LAYANAN PRIMER ( ILP ) POLA BIP TAHUN 2025',
            'PELATIHAN MANAJEMEN PUSKESMAS INTEGRASI LAYANAN PRIMER ( ILP ) TAHAP 1',
            'PELATIHAN MANAJEMEN PUSKESMAS INTEGRASI LAYANAN PRIMER ( ILP ) TAHAP 2',
            'PELATIHAN PENDIDIKAN INKLUSIF BAGI GURU PEMBIMBING KHUSUS',
            'PELATIHAN PENDIDIKAN INKLUSIF BAGI GURU PEMBIMBING KHUSUS ANGKATAN II',
            'PELATIHAN PENGEMBANGAN AGENS HAYATI BAGI POPT',
            'PELATIHAN PENGEMBANGAN KOMPETENSI BAGI KEPALA SEKOLAH ANGKATAN 1',
            'PELATIHAN PENGEMBANGAN KOMPETENSI BAGI KEPALA SEKOLAH ANGKATAN 2',
            'PELATIHAN PENGEMBANGAN KOMPETENSI BAGI KEPALA SEKOLAH ANGKATAN 3',
            'PELATIHAN PENGEMBANGAN KOMPETENSI BAGI PENGAWAS SEKOLAH',
            'PELATIHAN PENGUATAN WIDYAISWARA PADA SUBSTANSI PEMBELAJARAN AGENDA 1 s/d 4',
            'PELATIHAN PENYULUH KEAMANAN PANGAN (PKP) ANGKATAN I',
            'PELATIHAN PENYULUH KEAMANAN PANGAN (PKP) ANGKATAN II',
            'PELATIHAN PENYULUH KEAMANAN PANGAN (PKP) ANGKATAN III',
            'PELATIHAN PENYULUH KEAMANAN PANGAN (PKP) ANGKATAN IV',
            'PENGEMBANGAN KOMPETENSI BAGI KEPALA SEKOLAH ANGKATAN 1',
            'PENGEMBANGAN KOMPETENSI BAGI KEPALA SEKOLAH ANGKATAN 2',
            'PENGEMBANGAN KOMPETENSI BAGI KEPALA SEKOLAH ANGKATAN 3',
            'PENGEMBANGAN KOMPETENSI BAGI PENGAWAS SEKOLAH',
            'PENGEMBANGAN KOMPETENSI BAGI TENAGA ADMINISTRASI SEKOLAH ANGKATAN I',
            'PENGEMBANGAN KOMPETENSI BAGI TENAGA ADMINISTRASI SEKOLAH ANGKATAN II',
            'PENGEMBANGAN KOMPETENSI BAGI TENAGA ADMINISTRASI SEKOLAH ANGKATAN III',
            'PENGEMBANGAN KOMPETENSI BAGI TENAGA ADMINISTRASI SEKOLAH ANGKATAN IV',
            'PENGEMBANGAN KOMPETENSI BAGI TENAGA ADMINISTRASI SEKOLAH ANGKATAN V',
            'PENGEMBANGAN KOMPETENSI BAGI TENAGA ADMINISTRASI SEKOLAH ANGKATAN VI',
            'PENGEMBANGAN KOMPETENSI BAGI TENAGA ADMINISTRASI SEKOLAH ANGKATAN VII',
            'PENGEMBANGAN KOMPETENSI BAGI TENAGA ADMINISTRASI SEKOLAH ANGKATAN VIII',
            'PENGEMBANGAN KOMPETENSI BAGI TENAGA ADMINISTRASI SEKOLAH ANGKATAN IX',
            'PENGEMBANGAN KOMPETENSI BAGI TENAGA ADMINISTRASI SEKOLAH ANGKATAN X',
            'PKN Tingkat II Angkatan IV',
            'Prajab Gol II Angk.1',
            'Prajab Gol III Angk.1',
            'Prajab Gol III Angk.2',
            'Prajab Gol III Angk.3',
            'Prajab Gol III Angk.4',
            'Prajab Gol III Angk.5',
            'Prajab Gol III Angk.6',
            'Prajab Gol III Angk.8',
            'Prajab Gol III Angkt.7',
            'Program Eksekutif Daerah Angkatan I',
            'Program Eksekutif Daerah Angkatan II',
            'Program Eksekutif Daerah Angkatan III',
            'Program Eksekutif Daerah Angkatan IV',
            'TOC (Training Of Cours) Angk.1',
            'TOT (Training of Trrainers) perpustakaan',
            'TOT Pelayanan Administrasi Terpadu Kecamatan Angk.1',
            'TOT Rencana Pengamanan Air Minum (RPAM) Angkt.1',
            'TOT Tim Penilai Jabfungs Kesehatan Angkt.1',
            'ToT Orientasi DPRD',
            'Training Of Trainer (TOT) Pelatihan Kepemimpinan Pola Baru',
            'WORKSHOP E-LEARNING PENGARUSUTAMAAN GENDER (PUG)  DALAM  PEMBANGUNAN',
            'Workshop Peningkatan Kualitas Penyelenggaraan SPIP dan Manajemen Risiko Provinsi Jawa Tengah Tahun 2024',
            'Workshop Peningkatan Pelayanan Publik Berbasis Digital',
            'Workshop Penerapan Tingkat Komponen Dalam Negeri  (TKDN) dalam Pengadaan Barang Jasa Tahun 2024',
            'Workshop Penerapan Tingkat Komponen Dalam Negeri(TKDN)',
            'Workshop Penyusunan SKP',
            'Workshop Tematik Rumpun Ekbang',
            'Workshop Tematik Rumpun Pemerintah dan Kesra',
        ];

        $calendarData = [];
        foreach ($uniqueTitles as $title) {
            // Kita gunakan data tanggal dan lokasi dummy karena hanya 'title' yang penting untuk dropdown.
            $calendarData[] = [
                'title' => trim($title), // Membersihkan spasi di awal/akhir
                'description' => 'Deskripsi untuk ' . trim($title),
                'start_date' => '2025-01-01',
                'end_date' => '2025-01-01',
                'location' => 'BPSDMD Provinsi Jawa Tengah',
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        // Langkah 3: Masukkan data ke database
        // Menggunakan chunk untuk efisiensi jika data sangat besar
        foreach (array_chunk($calendarData, 200) as $chunk) {
            Calendar::insert($chunk);
        }
    }
}

